### ISSUE TITLE
Yarn v2+ support authentication to private registry

### ISSUE THREAD

**Issue by dlorych** [microsoft/azure-devops-extension-tasks#1041]
yarn v2+ has dropped usage of .npmrc file, hence npmAuthenticate@0 cannot be used anymore to authenticate to a private registry.

Is there any work going to to introduce "yarnAuthenticate" task?
Are there any workarounds to the problem?

**Comment by jessehouwing** [comment]
Please ask your question in the microsoft/azure-pipelines-tasks repository, this repo is for a set of very specific tasks used to publish new Azure DevOps extensions.
