### ISSUE TITLE
Feature Request: Ability to append string to each Task Name

### ISSUE THREAD

**Issue by deadlydog** [microsoft/azure-devops-extension-tasks#135]
I'm following [this advice](https://stackoverflow.com/a/56029399/602585) for how to test new changes of my extension before publishing them out to everyone. I'm using a different `Extension ID` and overriding the `Task ID` for my private extension. This allows me to publish my private version and test it out before publishing the public version.

The issue I have is that when I have both my public and private extension installed in my organization, I'm not able to tell which tasks belong to which extension, as the tasks from each extension have the same name. I do this because I want to be able to publish my private extension, exercise the tasks to validate them, and then publish the publish extension, and then exercise and validate those tasks.

To solve this issue, it would be great if we could specify a string that could be appended to all of the Task names. e.g. "(Internal)", or "(Testing)". This would allow me to easily tell which extension the task belongs to.

Thanks!

**Comment by jessehouwing** [comment]
I use a generic search & replace task or a jsonpatch task to achieve that.
It doesn't allow you to do binary promotion, but works like a charm.

https://github.com/jessehouwing/azure-pipelines-tfvc-tasks/blob/master/vsts-tfvc-add/task.json#L4



I recommend deployment to a separate org though.

**Comment by jessehouwing** [comment]
![Screenshot_20190514-072058](https://user-images.githubusercontent.com/4173387/57701917-4600bb80-765d-11e9-8351-fa8bb4ed27c9.png)
![Screenshot_20190514-072038](https://user-images.githubusercontent.com/4173387/57701955-54e76e00-765d-11e9-989c-a3444373150c.png)

**Comment by jessehouwing** [comment]
https://github.com/jessehouwing/azure-pipelines-tfvc-tasks/blob/master/vsts-tfvc-add/task.json#L4-L6

**Comment by deadlydog** [comment]
Cool, thanks for the links @jessehouwing 👍 . It would still be nice to have this functionality as a first-class feature though to make testing your extensions easier. I could use the same technique you described to update the task and extension version numbers, but that functionality is already a first-class feature of this extension so I might as well use it. I see updating the task names as falling into the same category, so I feel it makes sense to incorporate it into this extension as well.

> I recommend deployment to a separate org though.

That is an option, but it's not ideal because it doesn't allow me to have a fully automated pipeline. Publishing to a different organization would mean:

1. I commit my code and the deployment automatically publishes my private extension to my "other" organization.
1. I have to log into my "other" organization (which is also a pain) and manually kick off a build/deployment to exercise and test the new version of the extension.
1. If it succeeds (meaning all tests passed) then I have to log back into my "main" organization, and kick off the deployment of my public extension.

By installing both my private and public extension into the same organization, I can just commit my code and it will deploy the private extension, test it, and automatically publish the public extension; no manually intervention needed :) The only problem is it's hard to tell if the tasks belong to the private or the public extension that's installed.

**Comment by jessehouwing** [comment]
Yeah we have some task specific handling. Thing is, the more bells and whistles, the more to maintain. And when I do it tor tasks, people will want it for Connected Services, Ui extensions etc etc.

So unless tfx-cli absorbs these features and allows me to pass the request along, I'm hesitant to add more things that are easy to add through other already well supported tasks.
