### ISSUE TITLE
Query Extension Version does not increment version

### ISSUE THREAD

**Issue by Thilas** [microsoft/azure-devops-extension-tasks#136]
Hi,

I noticed very recently that Query Extension Version task not longer increments the version as expected:
```log
##[section]Starting: Query extension version
==============================================================================
Task         : Query Extension Version
Description  : Queries the current version from the Visual Studio Marketplace
Version      : 1.2.52
Author       : Microsoft Corporation
Help         : 
==============================================================================
[...]
Latest version   : 1.0.98.
Requested action : Patch.
Updated to       : 1.0.98.
##[section]Async Command Start: Update Build Number
Update build number to 1.0.98 for build 85343
##[section]Async Command End: Update Build Number
##[section]Finishing: Query extension version
```

Any ideas?

Thanks

**Comment by jessehouwing** [comment]
Looks broken. Would have to run some tests.

**Comment by jessehouwing** [comment]
I'm getting the right behavior on my account. Cak you run a Diagnosticr build and attach the logs?

```
##[debug]
Latest version   : 2.0.30.
Requested action : Patch.
Updated to       : 2.0.31.
##[debug]setBuildNumber=false
```

**Comment by Thilas** [comment]
Here are the logs: [logs_91889.zip](https://github.com/microsoft/azure-devops-extension-tasks/files/3211479/logs_91889.zip)

**Comment by jessehouwing** [comment]
My logs show `Patch`, yours `patch`. Are you by any chance using a YAML file to trigger the build or a bound variable? The current code is case sensitive. I'll make a note to ensure all options are checked for case sensitivity.

**Comment by Thilas** [comment]
Good catch, I am using indeed a yaml configuration. In the meantime, I'll fix the case. Thanks!

**Comment by Thilas** [comment]
The ticket has been closed. @jessehouwing, does that mean that something has been done on this topic?

**Comment by jessehouwing** [comment]
I've updated the tool tips a bit, but the current behavior is according to the specs.
