### ISSUE TITLE
How to make it work with vscode extensions?[QUESTION]

### ISSUE THREAD

**Issue by Raagh** [microsoft/azure-devops-extension-tasks#137]
I am trying to create a release pipeline for my vscode extension. Unfortunately I cant setup it correctly.

I am trying to use this extension by supplying the vsix file after packaging but it fails to find the manifest file( which should be the package.json right?)

Could you provide me with some guidelines on how to accomplish this?

**Comment by jessehouwing** [comment]
Vscode is not supported. Only vs, tfs and Azure devops
