### ISSUE TITLE
The process 'D:\a\_tools\tfx.cmd' failed with exit code 4294967295

### ISSUE THREAD

**Issue by Doetheman** [microsoft/azure-devops-extension-tasks#139]
When I try to run the Publish Extension build task I receive this error. \Windows\system32\cmd.exe /D /S /C "D:\a\_tools\tfx.cmd extension publish --json --no-color --service-url "marketplace link" --auth-type pat --token *** --root D:\a\1\s --manifest-globs vss-extension.json --loc-root D:\a\1\s --debug-log-stream stderr"  0 [ '[command]C:\\Windows\\system32\\cmd.exe /D /S /C "D:\\a\\_tools\\tfx.cmd extension publish --json --no-color --service-url "marketplace link" --auth-type pat --token *** --root D:\\a\\1\\s --manifest-globs vss-extension.json --loc-root D:\\a\\1\\s --debug-log-stream stderr"\r',   '' ]  1 [ '[command]C:\\Windows\\system32\\cmd.exe /D /S /C "D:\\a\\_tools\\tfx.cmd extension publish --json --no-color --service-url "market place link" --auth-type pat --token *** --root D:\\a\\1\\s --manifest-globs vss-extension.json --loc-root D:\\a\\1\\s --debug-log-stream stderr"\r',   '' ] error: Error: ENOENT: no such file or directory, lstat 'D:\a\1\s\bundle.js' 0 [ 'error: Error: ENOENT: no such file or directory, lstat \'D:\\a\\1\\s\\bundle.js\'',   '' ]  1 [ 'error: Error: ENOENT: no such file or directory, lstat \'D:\\a\\1\\s\\bundle.js\'',   '' ] ##[error]tfx failed with error: Error: The process 'D:\a\_tools\tfx.cmd' failed with exit code 4294967295

**Comment by jessehouwing** [comment]
My guess would be that the vss-extension.json references a file called bundle.js, which can't be found when invoking tfx.

**Comment by Doetheman** [comment]
I am using webpack to create that file. I also tried using a npm command to run the webpack script and publishing script which also did not work. Have you seen similiar issues or solutions for this?

**Comment by jessehouwing** [comment]
Run `dir /s` from a commandline task to ensure the files you want are there.

**Comment by Doetheman** [comment]
The bundle.js is not there.

**Comment by jessehouwing** [comment]
Then the issue is in the steps before the packaging job. Not the tfx step.
