### ISSUE TITLE
Use Node CLI for Azure DevOps - The "path" argument must be of type string

### ISSUE THREAD

**Issue by mmajcica** [microsoft/azure-devops-extension-tasks#142]
The task can't run in my case, I'm getting the above-mentioned message.

Attached the log file.
[tasklog_6.log](https://github.com/microsoft/azure-devops-extension-tasks/files/3446471/tasklog_6.log)

**Comment by jessehouwing** [comment]
Looks like an issue with the location of the tfx executable which isn't where I expect it to be...

**Comment by jessehouwing** [comment]
What version of NPM are you running? What OS?

**Comment by mmajcica** [comment]
Finally, I'm back to this issue. Sorry, it took me ages to focus on this again.
However,
npm -v -> 6.9.0
node -v -> 10.16.3
OS -> Red Hat Enterprise Linux Server 7.7
Kernel -> Linux 3.10.0-1062.1.1.el7.x86_64

AGENT_VERSION=2.159.2
AGENT_TOOLSDIRECTORY=/appl/agent.0/_tool

However, I think I figured out why of this. Seems that in case you use --prefix argument, the global configuration is ignored. I'll make some more investigation and if I do manage to fix it, I'll submit a PR with the fix, but also handle the failure of npm install a bit better so that the error message makes more sense then this.

**Comment by mmajcica** [comment]
I finally managed to understand this one. As mentioned above, if --prefix argument is used the global npmrc config file is ignored. The solution for me was to move the registry details into the user level npmrc and it all worked. Unfortunately, I haven't found a way to improve on the task so that the global npmrc gets passed in. I think that is not possible and it is a limitation of npm.
