### ISSUE TITLE
No longer authorized to publish extensions

### ISSUE THREAD

**Issue by JoeGaggler** [microsoft/azure-devops-extension-tasks#146]
We are no longer able to publish extensions using the Task, which claims that we are unauthorized:

![image](https://user-images.githubusercontent.com/27233871/63782304-d1225c00-c8b0-11e9-9d1b-6882ba78b82d.png)

The personal access token has not expired since the last successful run, however we did try to reset it as a troubleshooting step. We also tried using tokens for other Owners on the account.

We were able to successfully upload the extension manually using the portal, so the account attached to the personal access token is definitely authorized to publish.

**Comment by jessehouwing** [comment]
If the token was reset, has it been updated in Azure DevOps? have you tried the token locally? There isn't much the extension can do about bad tokens, the marketplace is denying access.

Contact vsmarketplace@microsoft.com for support.

**Comment by JoeGaggler** [comment]
It seems that Marketplace changed its requirements so that the personal access token must be authorized for "All accessible organizations" instead of the single organization that you are attempting to publish. 

Reference: https://code.visualstudio.com/api/working-with-extensions/publishing-extension

**Comment by jessehouwing** [comment]
That has been the case for a VERY long time.

**Comment by JoeGaggler** [comment]
@jessehouwing - that may be the case, and I'm not looking to reopen the ticket; but that does not seem align with our experience.

Our organization had only had one PAT that was permitted to publish extensions in a specific Azure DevOps pipeline, and that PAT did not expire within the relatively short window of time between successful and failed publish attempts:

![image](https://user-images.githubusercontent.com/27233871/67404653-4fca0b80-f579-11e9-8d2a-46369400eb6b.png)

Our first troubleshooting step was to renew the existing token without making any scope changes:

![image](https://user-images.githubusercontent.com/27233871/67404758-75571500-f579-11e9-8a20-b1a7f2015b93.png)

Renewal did not fix the issue, and fortunately we came across the above reference that suggested to expand the scope of the PAT.

Since this behavior is as-designed, no need to reopen this ticket, just wanted to share for anyone else who might be experiencing similar symptoms.

**Comment by jessehouwing** [comment]
It sounds like a temporary glitch on the marketplace side. Thanks for sharing your experience.

I've long hoped for a way to see failed api attempts with an explanation on WHY it failed.
