### ISSUE TITLE
Query the currently installed extension inside a build

### ISSUE THREAD

**Issue by andyli** [microsoft/azure-devops-extension-tasks#151]
Is it possible to query the version of the currently installed extension inside a build?

I notice there is "QueryAzureDevOpsExtensionVersion", but that's about the extension published to the marketplace, but not the currently installed version.

**Comment by jessehouwing** [comment]
In a specific account? There is an api for that, but not exposed through
tfx-cli.

I think you can get to the information using `az devops extension show`.

https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/devops/extension

**Comment by andyli** [comment]
Thanks for the suggestion. It's close but not quite. I found that the extension in a build can be different from the extension installed to an organization. When an extension has just been updated, if I check the version installed to the organization using `az devops`, it shows the updated version number, but when I start a new build right after the check, I can see that I'm still using the old version. A new build will only use the new version after awhile.

**Comment by jessehouwing** [comment]
See:
https://blogs.blackmarble.co.uk/rfennell/2018/03/20/using-vsts-gates-to-help-improve-my-deployment-pipeline-of-vsts-extensions-to-the-visual-studio-marketplace/

Since the REST API depends on the guid of the task(s), I've decided to not put them inside of the extension tasks.

**Comment by andyli** [comment]
I've just tried to call the api you mentioned in the blog post, but it's the same as the `az devops` cli - even the api returned the newly deployed task version, the immediate following jobs were still using the previous task version.

My test build: https://dev.azure.com/onthewings/GitHub%20public%20projects/_build/results?buildId=560&view=results
Here the api returned the installed version is `0.1.22`: https://dev.azure.com/onthewings/GitHub%20public%20projects/_build/results?buildId=560&view=logs&j=4a236b33-8953-571b-a437-f5ebbbc08e14&t=26b69268-2a58-5c49-d590-902442b8bd93&l=15
Here the job used the previous version `0.1.21`: https://dev.azure.com/onthewings/GitHub%20public%20projects/_build/results?buildId=560&view=logs&j=fa54a428-573f-5b7f-aa5c-3644957dfe2f&t=b78aa7d1-14fa-5a30-8e5b-a660c033a4e9&l=5

**Comment by jessehouwing** [comment]
I totally understand the frustration, but it's beyond the scope of this extension. I think this belongs to the service side of Azure Pipelines, making this the place to report the issue:

https://developercommunity.visualstudio.com/spaces/21/index.html
