### ISSUE TITLE
Unable to create Visual Studio Marketplace connection

### ISSUE THREAD

**Issue by warzinskid** [microsoft/azure-devops-extension-tasks#152]
This probably isn't an issue with the extension itself, but I can't find the option to create a Visual Studio Marketplace connection.  I clicked the Manage link to get to the service connections page, but there is no service or connection type that seems to match this.  Any suggestions?

**Comment by jessehouwing** [comment]
You're looking for an Azure DevOps Marketplace connection. Maybe with the addition of Visual Studio I should look at improving the name :).

**Comment by warzinskid** [comment]
Azure DevOps Marketplace isn't a connection option for me either :(

**Comment by jessehouwing** [comment]
![image](https://user-images.githubusercontent.com/4173387/68590080-f412e400-048d-11ea-851c-2e1a0cbb0d7c.png)

**Comment by warzinskid** [comment]
![image](https://user-images.githubusercontent.com/35928897/68592617-7fc24b80-0461-11ea-9e9a-a2b4cc7bf194.png)

Is there something I have to do to add that option?

**Comment by jessehouwing** [comment]
No clue. Other than uninstalling the extension and installing it again. Or filing or bug with Microsoft.

I'm not with Microsoft, but a volunteer contributor. I can't do anything on your azzount to provide support.

**Comment by warzinskid** [comment]
Reinstalling the extension made it available.  I appreciate the help.

This is a pretty sweet extension, I've had it working for almost 30 minutes and the team is already excited about using it.
