### ISSUE TITLE
Node10 execution handler

### ISSUE THREAD

**Issue by mmajcica** [microsoft/azure-devops-extension-tasks#153]
How so that we have both Node10 and Node execution handler in TfxInstaller?

**Comment by jessehouwing** [comment]
Node for old TFS versions. Node10 for new ones.

**Comment by mmajcica** [comment]
Isn't the Node10 provider only agent dependant and if I'm not mistaken it was introduced with agent version 2.144.0?

**Comment by jessehouwing** [comment]
I want to be prepared for node10 becoming the default. Node6 is pretty old and many modules no longer support it.
