### ISSUE TITLE
Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.

### ISSUE THREAD

**Issue by Bhsha** [microsoft/azure-devops-extension-tasks#154]
Build pipeline task “Publish Extension” started failing 2 days back with following error.
![image](https://user-images.githubusercontent.com/49294839/68969935-fb423680-079a-11ea-9e0e-4e6fde32e397.png)

I doubt this is the same [issue ](https://github.com/Microsoft/vscode-vsce/issues/332)reported for old version of tfx-cli extension as publish task is using older version – 0.5.14

![image](https://user-images.githubusercontent.com/49294839/68969912-efef0b00-079a-11ea-869a-b8a8a1dda289.png)
Can someone update the task to use newer version of tfx-cli package?

**Comment by jessehouwing** [comment]
Just use the tool installer task to install the latest version of tfx-cli.
Make sure the extension is updated to v2.0, this cleared a couple of errand
permissions and therefore requires admin approval.


- task: TfxInstaller@2
inputs:
version: 'v0.7.x'

**Comment by jessehouwing** [comment]
```
- task: TfxInstaller@2
inputs:
version: 'v0.7.x'
```

**Comment by Bhsha** [comment]
@jessehouwing thanks for the response. What extension should be updated to v2.0 as you mentioned in your first reply?

**Comment by Bhsha** [comment]
Also which tool installer task are you talking about? Can you share link or screenshot?

**Comment by jessehouwing** [comment]
See:

https://jessehouwing.net/azure-devops-extension-tasks-1-2-3x/

**Comment by Bhsha** [comment]
Latest version of the extension was not installed in the ADO project as it was under review for admin approval. However by doing so fixed the issue.

**Comment by kyle-rader** [comment]
I'm trying to resolve the same original issue here. After updating to the latest 2.x versions of the Use tfx and package extension tasks I'm now stuck on the following error.
```
error: Extension package is malformed/corrupted
```
Has anyone encountered this while upgrading. There have been no functional/content changes to our extension. I only incremented the version of tfx used.

**Comment by jessehouwing** [comment]
Add a variable to your pipeline and set it to:

```

TFX_TRACE=1

```

Hopefully that gives you more data.


What settings are you using to package? Was the package created with
the same version of tfx you're using to publish it?
