### ISSUE TITLE
Azure CLI Task throws an error and doesnt do work but task completes succesfully

### ISSUE THREAD

**Issue by alexatnext** [microsoft/azure-devops-extension-tasks#157]
Hi, when using the Azure CLI task i am getting the below error:

==============================================================================
Task         : Azure CLI
Description  : Run Azure CLI commands against an Azure subscription in a PowerShell Core/Shell script when running on Linux agent or PowerShell/Powershell Core/Batch script when running on Windows agent.
Version      : 2.0.4
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-cli
==============================================================================
(node:8400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'cleanUp' of undefined

This doesnt execute my script but does complete successfully.

**Comment by jessehouwing** [comment]
Correct place to report is here: 

 * https://github.com/microsoft/azure-pipelines-tasks/issues
