### ISSUE TITLE
Support different Authentication methods (KeyVault)

### ISSUE THREAD

**Issue by heatherjsun** [microsoft/azure-devops-extension-tasks#162]
I'm currently using the ADO extension tasks to query for extension version and publish an extension. I'm using a Visual Studio Marketplace connection, which only allows authentication using a PAT. We have PAT for our service account which we use to publish extensions, however there is no way of automating the update of this PAT.

For example, a [Azure Resource Manager service connection](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/connect-to-azure?view=azure-devops) can connect to an Azure Key Vault. Then this service connection can be linked to a [variable group](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/connect-to-azure?view=azure-devops), which can be referenced in an ADO pipeline. Thus allowing an ADO pipeline to reference a secret from the key vault.

If the tasks allowed users to explicitly pass in a PAT, without using the Marketplace service connection then my issue would be solved. Is that a possibility?

Or, if the Visual Studio Marketplace connection to allowed authentication with keyvault directly, that could work. Does anyone know who owns this type of service connection? 

Thanks for the help!

**Comment by jessehouwing** [comment]
Open for a pull request.

**Comment by jessehouwing** [comment]
You can manage service connections with the REST API to store a new PAT value

* [Create](https://docs.microsoft.com/en-us/rest/api/azure/devops/serviceendpoint/endpoints/create?view=azure-devops-rest-6.1&WT.mc_id=DOP-MVP-5001511)
* [Update](https://docs.microsoft.com/en-us/rest/api/azure/devops/serviceendpoint/endpoints/update%20service%20endpoint?view=azure-devops-rest-6.1&WT.mc_id=DOP-MVP-5001511)

**Comment by jessehouwing** [comment]
I'm closing this issue as I don't see a lot of extra value in supporting multiple secret sources.
