### ISSUE TITLE
The extension package size exceeds the maximum size limit

### ISSUE THREAD

**Issue by Or-Gabay** [microsoft/azure-devops-extension-tasks#165]
For some reason, my extension increased to a total of 30 MB:
`error: Failed Request: Bad Request(400) - The extension package size '30037289 bytes' exceeds the maximum package size '26214400 bytes`.
I don't know why but it used to be 20MB. How can I start to investigate this issue? is there a way to shrink it?

**Comment by Or-Gabay** [comment]
@jessehouwing, could you please point me to some examples regarding webpack & how to download azure-pipelines-task-tool-lib to local cache?

**Comment by jessehouwing** [comment]
Sample of a stand-alone tool installer:
https://github.com/microsoft/azure-devops-extension-tasks/blob/master/BuildTasks/TfxInstaller/

Sample of a built-in tool installer:
https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/UniversalPackagesV0/universalmain.ts
https://github.com/microsoft/azure-pipelines-tasks/blob/178db1b4ca07e11fdc6a76504b88b52e5a2663c3/Tasks/Common/packaging-common/universal/ArtifactToolUtilities.ts#L39

**Comment by jessehouwing** [comment]
I'll ask someone I know uses webpack to share something here...

**Comment by jessehouwing** [comment]
Let me know what you ended up doing, would be worth a nice blogpost. Possibly co-written.

**Comment by jessehouwing** [comment]
If you're not using webpack (or maybe even when you're using webpack) make sure you run `npm dedupe && npm prune --production` to shed the stuff you won't need.
