### ISSUE TITLE
updateTasksId should update task id in supportsTasks

### ISSUE THREAD

**Issue by Mobrockers** [microsoft/azure-devops-extension-tasks#166]
The supportsTasks property on a web contribution to conditionally display a pipeline view based on a task being available in the pipeline depends on the task id not the contribution id. As far as I can tell the supportsTasks id's are not currently replaced when using the updateTasksId option, which means custom pipeline tabs never become available.

At a minimum this should be documented on the option because it is very hard to debug as you can't reproduce this locally, only after deployment (and might already be in production).

**Comment by jessehouwing** [comment]
That sounds like a correct assertion. I don't have any tasks that use linked web contributions, nor did the customer for whom this feature was originally added. Would absolutely take a Pull Request to fix this.

**Comment by jessehouwing** [comment]
Or do you have a sample project I could use to try and poke at this myself?

**Comment by Mobrockers** [comment]
The project where I experienced this issue is here: https://github.com/stryker-mutator/azure-devops-mutationreport-publisher

**Comment by jessehouwing** [comment]
Won't likely have time to pick this up any time soon. will absolutely accept a PR, and of course I'd expect stryker verified unit tests for all the existing functionality ;).

**Comment by jessehouwing** [comment]
Quickest way to get this in seems to be to capture the before/after id when it's changed on this line an update the already loaded extension manifest.:

https://github.com/microsoft/azure-devops-extension-tasks/blob/main/BuildTasks/Common/Common.ts#L403

And then overwrite the extension manifest here:

https://github.com/microsoft/azure-devops-extension-tasks/blob/main/BuildTasks/Common/Common.ts#L421

There is a weird case that may need extra work... The task contribution may be stored in a different manifest than the web hub contribution point. See the example here where the extension point is in a second file:

https://github.com/jessehouwing/azure-pipelines-demo-ping-task/blob/main/vss-extension.multipingtask.json

**Comment by Mobrockers** [comment]
I might have time to take a look at this next week.

**Comment by jessehouwing** [comment]
Release is rolling out at the moment. Thanks for your contributions. Do let me know when you've implemented it and everything works according to plan.

**Comment by Mobrockers** [comment]
Unfortunately I don't think I can actually use this feature for my extension deployment due to that it's already publicly released and I'm worried it would break the task in production due to changed task id with same name 😅

**Comment by jessehouwing** [comment]
Use it only for test versions, ship the production version with the guids
specified in source.

**Comment by Mobrockers** [comment]
@jessehouwing I finally had time to change the pipeline for test and the change works 👍 💐
