### ISSUE TITLE
Documentation about how the service connection should be made is missing

### ISSUE THREAD

**Issue by KevinHale-Bentley** [microsoft/azure-devops-extension-tasks#169]
I tried guessing at which service endpoint type should be used to create the necessary service connection to the marketplace.  Regardless which option I chose, I ran into one of two issues:

1. PAT was denied.  I spoke to one of our Azure DevOps admins, and he could see no reason why the PAT wouldn't work.
2. The service connection dropdown on the task configuration page was empty

I tried finding this information elsewhere to no avail.

It would be helpful if the marketplace page for this set of tasks either linked to, or explicitly documented, the steps necessary to create the required service connection.

**Comment by jessehouwing** [comment]
1. PAT requirements are documented on the marketplace as well as on the PAT edit screen:

https://marketplace.visualstudio.com/items?itemName=ms-devlabs.vsts-developer-tools-build-tasks

2. As well as the Visual Studio Marketplace service connection page:

![Screenshot_20200717-205848.png](https://user-images.githubusercontent.com/4173387/87821626-697e5200-c870-11ea-98e0-96cd3d15d7df.png)

The service connections use the same icon as the extension itself.

I'm open to more documentation, but

**Comment by KevinHale-Bentley** [comment]
We don't have a "Visual Studio Marketplace" service endpoint type in our list.  Is that something that our admin needs to install?  Maybe that's the issue.  The reason that I asked for more documentation was that I thought we needed to use a different type (since none of our types mentioned 'marketplace' at all), so I thought this must be re-using another type (such as "Azure Repos/Team Foundation Server").

**Comment by jessehouwing** [comment]
Be sure that version 3.0.3 is installed and any permission requests have been resolved.

That endpoint type should be available. I'm not aware of any issues that may hide it. Maybe disabling/enabling the extension may make it appear.

If that won't work, uninstall/reinstall.

![IMG_20200717_211613.jpg](https://user-images.githubusercontent.com/4173387/87822979-c4b14400-c872-11ea-9504-4abc14104ebd.jpg)

**Comment by jessehouwing** [comment]
Were you able to make it work?

**Comment by KevinHale-Bentley** [comment]
I e-mailed the admin that I had been working with about your suggestions, but he hasn't replied yet.
