### ISSUE TITLE
Query Extension Version should not give error when extension is not in the marketplace yet (initial)

### ISSUE THREAD

**Issue by spoelly** [microsoft/azure-devops-extension-tasks#170]
When running my pipeline initially the task Query Extension gives an error that json is not correct.
After uploading the first vsix manual to the marketplace portal it never fails again the pipeline.

The version number of the VSIX should be used in the Publish step

snippet of yaml:

``` json
buildstages:
      - stage: Build_Extension
        jobs:
        - job:
          displayName: Package Extension
          pool:
            vmImage: windows-latest
          continueOnError: false
          steps:
          - checkout: self
            persistCredentials: true          
          - task: TfxInstaller@2
            displayName: Install Tfx-CLI on agent
            inputs:
              version: 'v0.7.x'
          - task: QueryAzureDevOpsExtensionVersion@2
            displayName: Get latest version of extension from Marketplace
            inputs:
              connectTo: 'VsTeam'
              connectedServiceName: '***********'
              publisherId: '***********'
              extensionId: 'ado2scsmTask'
              versionAction: $(versionAction)
              setBuildNumber: 'true'
          - task: PackageAzureDevOpsExtension@2
            displayName: Build vsix file of extension 
            inputs:
              rootFolder: '$(Build.SourcesDirectory)\ADO\ado2scsmTask'
              outputPath: '$(vsix)'
              extensionVersion: '$(Build.BuildNumber)'
              updateTasksVersion: true
          - task: PublishPipelineArtifact@1
            displayName: Publish Pipeline Artifacts
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)\vsix\'
              artifact: 'ado2scsmTask'
              publishLocation: 'pipeline'
```

> 0 [ '[command]C:\\windows\\system32\\cmd.exe /D /S /C "C:\\hostedtoolcache\\windows\\tfx\\0.7.11\\x64\\tfx.cmd extension show --json --no-color --service-url https://marketplace.visualstudio.com/ --auth-type pat --token *** --publisher ****** --extension-id ado2scsmTask"\r',
  '' ]
##[error]SyntaxError: Unexpected end of JSON input

**Comment by jessehouwing** [comment]
For the very first run, I'd personally disable the task. or you can set the `extensionVersionOverride` input to something other than nothing, which will skip the call to the marketplace. (You can pass in a variable which you can control through the variables tab or a variable library.

          - task: QueryAzureDevOpsExtensionVersion@2
            displayName: Get latest version of extension from Marketplace
            inputs:
              connectTo: 'VsTeam'
              connectedServiceName: '***********'
              publisherId: '***********'
              extensionId: 'ado2scsmTask'
              versionAction: $(versionAction)
              setBuildNumber: 'true'
              extensionVersionOverride: '$(extensionVersionOverride)'

![image](https://user-images.githubusercontent.com/4173387/88931603-56f71600-d27d-11ea-8468-e402714491e2.png)

It's also a good way to bump the major version, just pass in the new major version once at manual queue time.

I can't distinguish between "not yet published" and "not your extension" and "something went wrong". The marketpglace just gives me `error: Failed Request: Bad Request(400) - The extension ID 'vsts-ensire-tests-dev-xxx'' is invalid.`, but not WHY it is invalid.

**Comment by jessehouwing** [comment]
I'll see if I can write a better error message to the output. Not sure why it got lost.
