### ISSUE TITLE
Package extension tasks

### ISSUE THREAD

**Issue by zoemac11** [microsoft/azure-devops-extension-tasks#175]
Getting the following error on the new version of the package extension task
```
(node:2450) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
##[error]Error: The process '/opt/hostedtoolcache/tfx/0.7.11/x64/bin/tfx' failed because one or more lines were written to the STDERR stream
```

Working on Version      : 3.1.26
Broken on Version      : 3.1.33

Debug log
```

##[debug]matchOptions.noext: 'false'
##[debug]matchOptions.nocase: 'false'
##[debug]matchOptions.nonull: 'false'
##[debug]matchOptions.matchBase: 'false'
##[debug]matchOptions.nocomment: 'false'
##[debug]matchOptions.nonegate: 'false'
##[debug]matchOptions.flipNegate: 'false'
##[debug]pattern: 'vss-extension.json'
##[debug]findPath: '/home/vsts/work/1/s/extension/pre-pipeline-task/vss-extension.json'
##[debug]statOnly: 'true'
##[debug]found 1 paths
##[debug]applying include pattern
##[debug]adjustedPattern: '/home/vsts/work/1/s/extension/pre-pipeline-task/vss-extension.json'
##[debug]1 matches
##[debug]1 final results
##[debug]Found manifests: /home/vsts/work/1/s/extension/pre-pipeline-task/vss-extension.json
##[debug]Patching: /home/vsts/work/1/s/extension/pre-pipeline-task/vss-extension.json.
/opt/hostedtoolcache/tfx/0.7.11/x64/bin/tfx extension create --json --no-color --root /home/vsts/work/1/s/extension/pre-pipeline-task --manifest-globs vss-extension.json --loc-root /home/vsts/work/1/s/extension/pre-pipeline-task --overrides-file /tmp/PackageTask-0.275128.tmp --output-path /home/vsts/work/1/s 0 [ '[command]/opt/hostedtoolcache/tfx/0.7.11/x64/bin/tfx extension create --json --no-color --root /home/vsts/work/1/s/extension/pre-pipeline-task --manifest-globs vss-extension.json --loc-root /home/vsts/work/1/s/extension/pre-pipeline-task --overrides-file /tmp/PackageTask-0.275128.tmp --output-path /home/vsts/work/1/s',
  '' ]
 1 [ '[command]/opt/hostedtoolcache/tfx/0.7.11/x64/bin/tfx extension create --json --no-color --root /home/vsts/work/1/s/extension/pre-pipeline-task --manifest-globs vss-extension.json --loc-root /home/vsts/work/1/s/extension/pre-pipeline-task --overrides-file /tmp/PackageTask-0.275128.tmp --output-path /home/vsts/work/1/s',
  '' ]
(node:2498) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
##[debug]{
##[debug]    "path": "/home/vsts/work/1/s/task-0.24.0.vsix",
##[debug]    "extensionId": "build-release-task",
##[debug]    "version": "0.24.0",
##[debug]    "publisher": ""
##[debug]}
##[debug]
##[debug]
##[debug]
##[debug]task result: Failed
##[error]Error: The process '/opt/hostedtoolcache/tfx/0.7.11/x64/bin/tfx' failed because one or more lines were written to the STDERR stream
##[debug]Processed: ##vso[task.issue type=error;]Error: The process '/opt/hostedtoolcache/tfx/0.7.11/x64/bin/tfx' failed because one or more lines were written to the STDERR stream
##[debug]Processed: ##vso[task.complete result=Failed;]Error: The process '/opt/hostedtoolcache/tfx/0.7.11/x64/bin/tfx' failed because one or more lines were written to the STDERR stream
##[debug]Deleting temp file: /tmp/PackageTask-0.275128.tmp
```

**Comment by jessehouwing** [comment]
That warning seems to come from tfx, can you increase the version to 0.8.x
to see if that solver the issue?

**Comment by zoemac11** [comment]
Same error

**Comment by jessehouwing** [comment]
Lemme see if I can repro. Nope...

It looks like a bug in tfx... It isn't supposed to leak node warnings to
the output. Not sure what causes your code to trigger that path.

Do you have any specific node environment variables or config items on your
end?

Can I get access to the pipeline and/or the sources?

**Comment by zoemac11** [comment]
Can try get you permissions to it. 

Nothing actually changed within the package so confused at why this bug has appeared now?

**Comment by jessehouwing** [comment]
I'm suspecting something changed in the dependencies of tfx-cli. The
pipeline fetches a new instance every time, but while the tfx code itself
may not have changed, it downloads a gazillion of dependencies every time
and those change regularly.

**Comment by zoemac11** [comment]
[pre-pipeline-task.zip](https://github.com/microsoft/azure-devops-extension-tasks/files/5500014/pre-pipeline-task.zip)

Added a zip of the sources and pipeline files. If you need anything else let me know.

Thanks

**Comment by jessehouwing** [comment]
This version hopefully fixes the issue for now, I still can't repro on my environment...

https://dev.azure.com/jessehouwing/azure-devops-extensions/_build/results?buildId=2379&view=results

If you have an org name, I can share this version for verification.

**Comment by tapasudenia** [comment]
So I assume, the version 3.1.35 is not available publicly yet, correct? As the last step was skipped in your pipeline. Because I tried uninstalling and installing back the extension, got the same version 3.133.

**Comment by jessehouwing** [comment]
I need someone to verify the fix and that it doesn't cause more issues, as I'm not having issues with any of my 8 extensions. Ef you have an org name, I can share the dev version with you.

**Comment by jessehouwing** [comment]
Real culprit here is likely some change in a dependency of tfs-cli: https://github.com/microsoft/tfs-cli/issues/360

**Comment by tapasudenia** [comment]
This is the exact warning I am getting too.

**Comment by jessehouwing** [comment]
What your azure devops organization name?

**Comment by tapasudenia** [comment]
msi-cie

**Comment by jessehouwing** [comment]
And what node version are you targetting? tfx doesn't seem to be prepared for node14 and 15 yet.

**Comment by jessehouwing** [comment]
shared:
https://marketplace.visualstudio.com/items?itemName=jessehouwing.vsts-developer-tools-build-tasks-dev

**Comment by jessehouwing** [comment]
bedtime here now. If 3.1.35 works for you I'll promote it tomorrow.

**Comment by tapasudenia** [comment]
Ok Thanks. I will update here

**Comment by tapasudenia** [comment]
Version 3.1.35 worked no more STDERR stream error. Thanks for the help.

**Comment by tapasudenia** [comment]
You can publish to market place and  we can start using the Marketplace version of the extension.

**Comment by zoemac11** [comment]
Thanks, my issue is now fixed.
