### ISSUE TITLE
[Check Marketplace validation status] task fails when service connection has been updated via the new service connection UI

### ISSUE THREAD

**Issue by mpth** [microsoft/azure-devops-extension-tasks#179]
Just ran into this issue again after I regenerated a PAT and updated the extension marketplace service connection via the new UI

```
============================================================================== 
Task         : Check Marketplace validation status: [extensionId]
Description  : Check Marketplace validation status.
Version      : 3.1.37
Author       : Microsoft Corporation
Help         : 
============================================================================== 
2020-11-12T10:57:15.0922182Z GET https://marketplace.visualstudio.com/_apis/gallery/publishers/[publisher]/extensions/[extensionid]?flags=1
				Response Code: 0
				Response: An error was encountered while processing request. Exception: 
Exception Message: Variable with name endpoint.username could not be found for the given service connection. (type ServiceEndpointException)
				Evaluation of expression 'or(eq(count(jsonpath('$.versions[?(@.version==''latest'' && @.flags==''validated'')]')), 1), and(in('latest', 'latest', ''), eq(jsonpath('$.versions[0].flags')[0], 'validated')))' failed.
				
Exception Message: Error parsing API response into a JSON object. (type DistributedTaskException)
```

Last time I was able to fix it by reverting to the old service connection UI and updating the connection there but that is not possible anymore today.

It looks like the new UI behaves differently so that the `auhtorization.parameters.username` property is not set at all instead of an empty string leading to the http request checking for extension status to fail with the error above .  

I was able to fix the error by updating the service connection by using the REST api directly setting a username

```
PUT https://dev.azure.com/[org]/_apis/serviceendpoint/endpoints/[endpointId]?api-version=6.1-preview.4`

{
...
    "authorization": {
        "parameters": {
            "username": "myemail@example.com",
            "password": "mypersonalaccesstoken"
        },
        "scheme": "UsernamePassword"
    }
...
}

```

I looked at the the repo to check whether it is possible to fix this in the task but didn't find an obvious place to fix it. 

Maybe this actually needs to be fixed in Azure DevOps?

**Comment by jessehouwing** [comment]
They've been messing with the service connections for a while now.

**Comment by jessehouwing** [comment]
Can you report it on developer connection? It's a bug in the product, but
I'm afraid I will need to find a workaround.

**Comment by mpth** [comment]
Posted it in the Developer Community https://developercommunity.visualstudio.com/content/problem/1254062/new-service-connection-ui-breaks-task-check-market.html

**Comment by jessehouwing** [comment]
I'm chatting with a member of the team at Microsoft tomorrow about this problem.

**Comment by jessehouwing** [comment]
Talked to the team, internal bug has been filed will be updated on status.
