### ISSUE TITLE
Azure devops extension task not working with azure devops server2020.

### ISSUE THREAD

**Issue by Gautami1074** [microsoft/azure-devops-extension-tasks#180]
Azure DevOps extension task not working with azure DevOps server2020.And for an access token, it is showing that **"Personal Access Token (TFS 2017+ and Azure DevOps Server 2019).** And if we use it in the Release it gives error like **"error: Received response 401 (Not Authorized). Check that your personal access token is correct and hasn\'t expired"**
Let me know when I can get an updated version.

**Comment by jessehouwing** [comment]
As far as I can tell these is no update needed from our end to support Azure Devops Server 2020. Other than updating the help text.

Make sure the token has all the required scopes. And try a "all scopes" token to see if that fixes things.

**Comment by Gautami1074** [comment]
Hi,

We have used token with full access.

**Comment by fleckert** [comment]
Does the setting  "All accessible organizations" for 'organization' make a difference?

**Comment by Gautami1074** [comment]
Yes, the error is changed to **'error: The given key was not present in the dictionary.'**

**Comment by jessehouwing** [comment]
Duplicate:
https://github.com/microsoft/azure-devops-extension-tasks/issues/171

That's a bug in Azure DevOps Server or TFX. Nothing I can do about that.
