### ISSUE TITLE
Package Extension task does not update task.loc.json version in same location as task.json

### ISSUE THREAD

**Issue by lechacon** [microsoft/azure-devops-extension-tasks#184]
The Package (or Publish) Extension task does not find the `task.loc.json` file when it is in the same location as the `task.json` (and not under a localization root). Since it doesn't find the file, it cannot update the version or id. The code seems to try looking in the task root if no localization root is provided in [this line](https://github.com/microsoft/azure-devops-extension-tasks/blob/ebb1796c20edd0c93908ba509a3e2bb7a1945fe1/BuildTasks/Common/Common.ts#L529):
```
let localizationRoot = tl.getInput("localizationRoot", false);
...
const rootLocManifest: string = path.join(localizationRoot || taskRoot, "task.loc.json");
```
but the logs suggest that `localizationRoot` is initialized even if not provided as input or set to empty:
```
##[debug]localizationRoot=D:\a\1\s
```

My guess is that since it is declared as a file path, when it is empty it defaults to the source root.

**Comment by jessehouwing** [comment]
Hmmm.... Yeah, this is where the framework has a few stupid internal behaviors. I'll have to think about how to deal with this. Making it a string for now will probably be the easiest workaround.

**Comment by jessehouwing** [comment]
Any chance you could test this fix on your end? I don't own localized extensions...

**Comment by jessehouwing** [comment]
I need an Azure DevOps account to share the extension to or you can steal the vsix from here:
https://dev.azure.com/jessehouwing/azure-devops-extensions/_build/results?buildId=2400&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by lechacon** [comment]
Thanks! I tried with the vsix and it worked :)

Logs were like this:
```
##[debug]Found task: <TaskName>
##[debug]localizationRoot=D:\a\1\s
##[debug]Absolute path for pathSegments: D:\a\1\s = D:\a\1\s
##[debug]build.sourcesDirectory=D:\a\1\s
##[debug]Absolute path for pathSegments: D:\a\1\s = D:\a\1\s
##[debug]localizationRootpath supplied :false
##[debug]Found single-task manifest: D:\a\1\s\<tasksRoot>\<TaskName>\task.json
##[debug]Found localized single-task manifest: D:\a\1\s\<tasksRoot>\<TaskName>\task.loc.json
```

**Comment by jessehouwing** [comment]
I'll run a few tests myself and will publish in the upcoming days. Thanks
for verifying.
