### ISSUE TITLE
Add support to unpublish an extension

### ISSUE THREAD

**Issue by cristianfilipe** [microsoft/azure-devops-extension-tasks#193]
Hey there. 
We've been using these extensions to do a complete dev/test publication of our own extensions, but for now, we are unable to remove those (with this extension) from the gallery after the testing is done. 
Is there a roadmap for this to be implemented?

PS: We are currently doing that using REST APIs.

Thank you!

**Comment by jessehouwing** [comment]
Adding it should be doable, it's supposed by Tfx-CLI.
https://www.github.com/Microsoft/tfs-cli/tree/master/app%2Fexec%2Fextension%2Funpublish.ts

I'd like to understand better why you'd want this functionality, in none of my work flows do I need to throw away the test versions, I keep reusing the same extension and just publish a new test version over it.

**Comment by jessehouwing** [comment]
Looks like that ain't too hard to do. Let's see if this works:
https://github.com/microsoft/azure-devops-extension-tasks/tree/feature/unpublish

**Comment by jessehouwing** [comment]
Rolling out this afternoon...

**Comment by jessehouwing** [comment]
The unpublish command gives 0 feedback other than "success"... So it may not always do what is says.

**Comment by jessehouwing** [comment]
Version | 3.1.60
-- | --
Released on | 6/7/2016, 2:21:28 PM
Last updated | 3/26/2021, 2:32:24 PM
Publisher | Microsoft DevLabs

**Comment by cristianfilipe** [comment]
Thank you!!

**Comment by cristianfilipe** [comment]
Hey,
When testing the new 'unpublish' feature, we got a 401 error. When double-checking the pipeline, I noticed that the 'server-url' parameter was missing.
I also checked the code and I notice that the function `common.setTfxMarketplaceArguments(tfx, false);` is been called with the false parameter.
I am wondering if this is related to the issue. 
Thank you!

**Comment by jessehouwing** [comment]
My guess is you need to update your PAT token with Marketplace (manage)
scope. That wasn't needed before, but unpublish requires it.

Not setting the url is the default behavior,that way tfx-cli uses it's
default configuration, which should be ok for Azure DevOps Marketplace.

**Comment by cristianfilipe** [comment]
Hello,
Yes, when we tried, we had already updated the token with this permission.
I don't know if this can impact, but we are using Azure DevOps Server (on premises).
Thank you!

**Comment by jessehouwing** [comment]
That may indeed be the case. I tested only against the public marketplace,
it's been a while I've used the server. In that case it may indeed need to
remove that boolean.

**Comment by cristianfilipe** [comment]
It is working now.
Thank you!
