### ISSUE TITLE
How do you get it to actually bump the version in the repo containing the extension?

### ISSUE THREAD

**Issue by jessehouwing** [microsoft/azure-devops-extension-tasks#207]
https://github.com/microsoft/tfs-cli/issues/262#issuecomment-901272916

For those using "Azure DevOps Extension Tasks extension" to bump the version of the extension/tasks - How do you get it to actually bump the version in the repo containing the extension? As it only updates the version in the artifact/code downloaded by the agent and lives in the agent's working directory. Meanwhile the version in the actual repo containing the extension code remains the same. And next time you make a change to the extension and run the pipeline to publish, it errors because it tries to bump the version to the same number it did last time.

**Comment by jessehouwing** [comment]
The extension expects you pass in a version as a parameter. Our own pipeline uses the Build.BuildNumber variable which is automatically incremented by Azure Pipelines each build.

Instead you can also use the Query Version task to read the current version from the Azure DevOps Marketplace and use that as a basis.

We don't store the actual version in Git, but only the base version, as explained here:

https://jessehouwing.net/vsts-relnote-ci-cd-tools-for-vsts-extensions-1-1-75/

In your sources ensure that the task.json for each task has the appropriate major (and optionally minor) version set.

```
vss-extension.json { "version": 3.2.1 }
- MultiVersionBuildTask
  - MultiVersionBuildTaskV1
    - task.json { "version": 1.0.0 }
  - MultiVersionBuildTaskV2
    - task.json { "version": 2.0.0 }
  - MultiVersionBuildTaskV3
    - task.json { "version": 3.0.0, "preview": true }

- SingleVersionBuildTask
  - task.json { "version": 1.0.0 }
```


Note: Remember, each version requires its own set of powershell/node modules.

It's possible to mix multi-version tasks and single version tasks in the same extension, however, they must follow the same Version Override Scheme.

**Comment by jessehouwing** [comment]
@pbcahill

**Comment by pbcahill** [comment]
@jessehouwing these are great options and exactly the sort of thing I was looking for. As we obviously don't want the actual repo changed from this pipeline process. Thank you!
