### ISSUE TITLE
ApplicationInsights timesout in Azure DevOps build task (node js)

### ISSUE THREAD

**Issue by kh-yash** [microsoft/azure-devops-extension-tasks#210]
I have developed an azure devops task extension that is installed in our pipeline. This task sends telemetry to Azure App Insights to record metrics and events. App Insights js library is throwing the following error in some of the builds.

ApplicationInsights:AzureVirtualMachine [ { Error: connect ETIMEDOUT 169.254.169.254:80
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
errno: 'ETIMEDOUT',
code: 'ETIMEDOUT',
syscall: 'connect',
address: '169.254.169.254',
port: 80 } ]

Does anyone know what could be the potential problem?

**Comment by jessehouwing** [comment]
This repository is histing the code for the **Azure DevOps Extension Tasks** extension. A set of tasks that help with automating the release process of Azure DevOps extensions.

This, unfortunately for you, isn't the place to ask for help about other tasks.

I recommend asking a question on StackOverflow instead.

If I'd had to guess there is a proxy or firewall in place blocking the outgoing traffic.
