### ISSUE TITLE
Publish Fails on Azure Hosted Agent Windows Latest

### ISSUE THREAD

**Issue by szavoda** [microsoft/azure-devops-extension-tasks#217]
I have been using the VISX Publish extension without issue using a Azure Hosted Agent under vs2017-win2016.  As that is being depreciated, I moved to Windows Latest image.  After that, the publish was failing unable to find "vsixpublisher.exe".

I opened a case with Devops Support, but they verified that the required components were installed and perhaps that this was a requirement of the extension for a particular extension and that I should open a bug here.  Here is a snippet of that conversation:

> After my research, please see my findings, our support scope and recommendations for this case:

> I was able to find that the task is failing because it could not locate “vsixpublisher.exe” and according to the error it is related to the “Microsoft.VisualStudio.Component.VSSDK”, but the Microsoft-Hosted agents indeed have the SDK installed:

> Windows-2019:

 
![image](https://user-images.githubusercontent.com/15132769/162087897-67b9b312-d165-40d2-b8d2-821dd48cc71b.png)

 
> Windows-2022:

 
![image](https://user-images.githubusercontent.com/15132769/162087913-c8b42880-e9e8-4c51-8ca2-a685263cc1b7.png)

 
> The problem could be related to the version the task requires, however this falls outside of the scope of our support, our support is what is called break and fix, we identify and work on issues that are related to the resources offered by DevOps.
 
> In this case the extension Azure DevOps Extension Tasks - Visual Studio Marketplace, that you are using is developed by Microsoft  DevLabs, and this type of extensions are experimental resources and their support should be addressed directly within the repositories of every extension. This is documented on this link: Publisher Microsoft DevLabs - Visual Studio Marketplace. I recommend you to open a bug directly from the repo and inform about the issue you are presenting, you can get access to the repo if you go to the Q&A section.

**Comment by jessehouwing** [comment]
https://github.com/microsoft/azure-devops-extension-tasks/blob/main/BuildTasks/PublishVSExtension/Utils.ts#L11

Looks like we search for a pretty specific version of vsixpublisher.exe. I don't think this is actually needed...

**Comment by szavoda** [comment]
@jessehouwing - Is it specific?  I am not familiar with the tool, but "-version [15.0,17.0)" looks like a range between 15 and 17.  I can verify I tested with windows-2019 and still had problems.

**Comment by jessehouwing** [comment]
Running a release now, can I share a dev version to your organization to verify the fix? If so, what org?

**Comment by szavoda** [comment]
@jessehouwing InfinityBehavioral - thanks!

**Comment by jessehouwing** [comment]
Shared.

**Comment by szavoda** [comment]
@jessehouwing embarrassed to admit, but I am not sure how to consume a shared dev version.

**Comment by jessehouwing** [comment]
You need to uninstall the official version temporarily, then install the dev version from your organization so "shared" tab in the manage extensions panel.

![Screenshot_20220408-200206](https://user-images.githubusercontent.com/4173387/162496910-df9e7b65-b732-4fbb-b2f3-77cc6fe9f4d8.png)

**Comment by szavoda** [comment]
Got it.  I tested successfully.  Thanks again!

**Comment by jessehouwing** [comment]
I'll be releasing the new version then. Proceed by uninstalling the dev version and reinstalling the official one.

**Comment by jessehouwing** [comment]
You're very welcome! Thanks for the bug report.

If this helped you, please:

* ⭐ Star the repo
* ⭐⭐⭐⭐⭐ Leave a review on the Azure DevOps Marketplace with a short description how these tasks helped you and what you are using the for:
  * 🛍️ [Azure DevOps Extension Tasks](https://marketplace.visualstudio.com/items?itemName=ms-devlabs.vsts-developer-tools-build-tasks)
* 💝 Consider sponsoring me or convince your employer to do so
