### ISSUE TITLE
Querying extension version with an extensionId that does not exist fails the task

### ISSUE THREAD

**Issue by madkoo** [microsoft/azure-devops-extension-tasks#218]
When querying extension version with an extensionId that does not exist returns null but the extension task fails on that. Should fall back to the version that's in the manifest.

**Comment by jessehouwing** [comment]
The behavior when no current version exists is undefined. Right now you have a few options to work around this:

 * Create an ExtensionVersion variable, assign the default value or read it from the manifest from your workflow.
 * Set the Continue on error to true.

Another option:

 * Create an OverrideVersion variable and make it assignable on queue.
 * In case of failure, specify the override version to use

Relying on the manifest is tricky, as there is no guarantee the manifest is available when the task runs.
