### ISSUE TITLE
Publish as GitHub Actions

### ISSUE THREAD

**Issue by JamieMagee** [microsoft/azure-devops-extension-tasks#227]
I understand that these are Azure Pipelines tasks for publishing Azure DevOps extensions. But, is it possible to package these as tasks as GitHub actions to enable publishing Azure DevOps extensions from GitHub?

**Comment by jessehouwing** [comment]
That's been in my plans for a while now, but I haven't gotten to that.

I have a few extensions I publish from actions and I've written a bit of pwsh to do most if this stuff for me.

https://github.com/jessehouwing/azure-pipelines-tasks-zips
https://github.com/jessehouwing/azure-pipelines-pre-and-post-tasks

**Comment by JamieMagee** [comment]
I took some inspiration from your PowerShell scripts and the tasks in this repo, and I've started writing my own GitHub Actions: https://github.com/JamieMagee/azure-devops-extensions-actions.

Once I'm happy with the features and stability, I'll see about moving them into the `microsoft` GitHub org

**Comment by jessehouwing** [comment]
Pretty cool. I was hoping to merge the different tasks into a single one and there are a few things that changed in TFX that the tasks here haven't incorporated due to the fact that they predate the changes by a long time.

I'd live to have a chat and then help on this. It's been a long time a co-contributor has spent time on this extension.

**Comment by JamieMagee** [comment]
I think the individual tasks are still quite useful, but I agree there is some technical debt.

It would also be possible to produce both Azure Pipelines Tasks and GitHub Actions using the same codebase. See https://github.com/microsoft/accessibility-insights-action for an example of this.

However, for the short term I'd like to complete my PowerShell-based GitHub Actions.
