### ISSUE TITLE
Speed up publishing from VSIX (preview)

### ISSUE THREAD

**Issue by jessehouwing** [microsoft/azure-devops-extension-tasks#326]
In one of my other projects I'm no longer extracting the whole vsix, only the manifest files needed to patch the extension. This saves a lot of time.

See:

 * https://github.com/jessehouwing/azure-pipelines-tasks-zips/blob/main/generate-sxs.ps1#L96
 * https://github.com/jessehouwing/azure-pipelines-tasks-zips/blob/main/generate-sxs.ps1#L137

```
$7zOutput = & "C:\Program Files\7-Zip\7z.exe" x $task -o_tmp task*.json *.resjson -r -bd
$7zOutput = & "C:\Program Files\7-Zip\7z.exe" u "$outputDir\$taskzip" "*" -r -bd
write-output "Created: $taskzip"
```

This code only handles the taskzips, so it should be updated to include the extension manifest files.

Time saving minutes for large extensions.

* [x] Add support for Windows (7z)
* [x] Add support for Mac and Linux (zip/unzip)
* [x] [Blog about the new feature](https://jessehouwing.net/speeding-up-the-azure-devops-extension-tasks/)
* [x] [Turn preview feature on by default](https://github.com/microsoft/azure-devops-extension-tasks/commit/9280715c5b246ddd89ccb0f2348be0722f505dcf).
* [x] Remove preview flag

In case of issues, turn off fast publish by setting the following variable:

```
variables:
- name: PREVIEW_FAST_UPDATE
  value: false
```

**Comment by AminTi** [comment]
Thanks for reporting.

**Comment by jessehouwing** [comment]
Interesting... Someone else starting to monitor the issues here...

FYI, this was mostly a note to self, but if anyone cares enough to pick this up, be my guest :D.

**Comment by jessehouwing** [comment]
Adding functionality behind a feature toggle.

Set variable `PREVIEW_FAST_UPDATE=true` for the workflow.

**Comment by jessehouwing** [comment]
Adding functionality behind a feature toggle.

Set variable `PREVIEW_FAST_UPDATE=true` for the workflow.

**Comment by jessehouwing** [comment]
Preview flag removed.
