### ISSUE TITLE
[Now in preview] Add support for Azure AD service Principals

### ISSUE THREAD

**Issue by jessehouwing** [microsoft/azure-devops-extension-tasks#506]
I've created a sample workflow that uses a AzureCLI step to overwrite the PAT with a OIDC job token:

https://jessehouwing.net/publish-azure-devops-extensions-using-workload-identity-oidc/

In the future I want to move that functionality straight into the task.

**Comment by pownkel** [comment]
+1, PAT tokens must be rotated manually and long-lived PATs are a potential security risk. My team would find it very helpful if there was a built-in way to use AD/Entra tokens for these tasks.

**Comment by michvllni** [comment]
+1, especially now as MSI and service principal authentication are out of preview in Azure DevOps

**Comment by jessehouwing** [comment]
@michvllni Make sure you check out the blog, it allows you to already switch over.

**Comment by DefaultRyan** [comment]
> @michvllni Make sure you check out the blog, it allows you to already switch over.

Could you link that blog? Many orgs are righteously clamping down on PAT usage, so I want to know more about what my PAT alternatives are.

**Comment by smfields** [comment]
@jessehouwing there are some scenarios where overriding service connection values using task.setendpoint is blocked due to [restricted commands](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/target?view=azure-pipelines#targetobjectproperties).

It would be really great to have this as part of the task itself for those scenarios where the workaround doesn't work.

**Comment by tintse-thxsky-MSFT** [comment]
Is there an ETA for merging https://github.com/microsoft/azure-devops-extension-tasks/commit/204ae1836e54ff5d03409768b0e075a4f00eec7a to main branch?  This help for those that uses version query.

**Comment by jessehouwing** [comment]
> Is there an ETA for merging https://github.com/microsoft/azure-devops-extension-tasks/commit/204ae1836e54ff5d03409768b0e075a4f00eec7a to main branch?  This help for those that uses version query.

Version query should work fine with the workaround described in my blog.

I originally started with this hack, but I don't want to support yet another sneak-solution to infinity.

**Comment by tintse-thxsky-MSFT** [comment]
@jessehouwing Yea the workaround in your blog is helpful, but for me the setendpoint doesn't work.  I suspect it is because my WIF is connecting to a **different** tenant.  And due to policy/design I can't move the service principal to the same tenant with my azure devops.

**Comment by jessehouwing** [comment]
Then the environment variables override isn't going to help you I'm afraid.

**Comment by jessehouwing** [comment]
Then the environment variables override isn't going to help you I'm afraid.

**Comment by jessehouwing** [comment]
Just merged #905 through #906. Made a few more changes. Awaiting publication of test builds. Thanks @50Wliu  <3

**Comment by tintse-thxsky-MSFT** [comment]
@jessehouwing  Sorry I am not familiar with the flow of release of this task.  When will the v5 be available to use? Can't wait to use it :)

**Comment by jessehouwing** [comment]
First pipelines now running v5. Doing a bit more testing, then shipping tomorrow

https://github.com/jessehouwing/azure-pipelines-variable-tasks/commit/a994947ee154606607f9c55f09dd42aba42c831c
https://dev.azure.com/jessehouwing/azure-devops-extensions/_build/results?buildId=5743&view=results

**Comment by jessehouwing** [comment]
Please upgrade your projects and report back with any issues you find.

**Comment by 50Wliu** [comment]
Hmm. I successfully log in, but then I get `##[error]__dirname is not defined` when trying to publish a VS extension.

**Comment by 50Wliu** [comment]
Oh, because https://github.com/microsoft/azure-devops-extension-tasks/blob/main/BuildTasks/PublishVSExtension/v5/Utils.ts#L10. I'll send in a PR later.

**Comment by jessehouwing** [comment]
* https://github.com/microsoft/azure-devops-extension-tasks/releases/tag/v5.0.65

**Comment by jessehouwing** [comment]
@stevenveerbeek The issue is closed, it's shipped.
