### ISSUE TITLE
Support Output variables

### ISSUE THREAD

**Issue by jessehouwing** [microsoft/azure-devops-extension-tasks#65]
https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/outputvariable.md

**Comment by pabrams** [comment]
I already see "Output Variable" fields in some of the tasks.  Should I avoid using those?

**Comment by jessehouwing** [comment]
No those work fine.

It's a dillema for me. I can't enable the new output variables without
breaking support for tfs 2015 and 2017. So unless Microsoft comes up with a
nice backwards compat model the old thing I can do is adding them both.

So the current output variables are here to stay for a while.
