### ISSUE TITLE
Publish Visual Studio Extension: Publish Fails in Azure DevOps with Unhandled Exception on Windows-2022 Agent

### ISSUE THREAD

**Issue by psxvoid** [microsoft/azure-devops-extension-tasks#706]
**Additional context**

Hi,

I've tried to deploy (publish) my extension in Azure DevOps pipeline but the deployment failed during the publishing. Though, I see `##[error]Error: Login failed.` output in the logs, it seems like the problem is not related to the login (explained why below). Here is the screenshot of the log output:

![image](https://github.com/microsoft/azure-devops-extension-tasks/assets/11395921/67b28b94-6d79-4883-8224-38d16be0cfc1)

Please, notice:

1. I'm using `windows-2022` build agent (`windows-latest` produces the same log).
2. The extension is able to login correctly because we can see `2023-11-22T11:00:57.1387384Z VSSDK: information VsixPub0041 : Publisher 'XYZ' is now logged-in.` line in the log output.
3. The error most likely is caused by `Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Memory` which we can see on the screenshot.
4. Extension Version: `4.3.94`

Also, I've tried to publish the extension from my local machine with **the same PAT**, and it was successful:

![image](https://github.com/microsoft/azure-devops-extension-tasks/assets/11395921/edcc930d-5693-4b82-bf66-efc9df19f842)

**Comment by jessehouwing** [comment]
I'm guessing it's a bug in Visual Studio 17.8 which was just released to the hosted agents. The fact that your machine works with 17.7 only strengthens my suspicion...

**Comment by psxvoid** [comment]
I believe you are correct, because somebody already submitted a similar issue at the Visual Studio Developer Community:

[Unable-to-publish-to-marketplace](https://developercommunity.visualstudio.com/t/Unable-to-publish-to-marketplace---VsixP/10011817?q=vsixpublisher&sort=newest)

The issue can be closed then, thanks @jessehouwing

**Comment by jessehouwing** [comment]
Leds leave it open for others to find until this functionality has been restored on the hosted agents.

**Comment by 50Wliu** [comment]
I'm hitting this too, but I'm not convinced the issue @psxvoid listed is the same. In that issue, they at least get far enough that the publish can spit out a warning (VsixPub0029). Here it just seems to crash.
I created a new Developer Community bug here: https://developercommunity.visualstudio.com/t/VsixPublisher-crashes-with-SystemIOFil/10552685?port=1025&fsid=0bb568d8-4630-497b-9b5e-cbff7d965a07

**Comment by 50Wliu** [comment]
FYI, this is fixed for me :).
