### ISSUE TITLE
TfxInstaller: Unable to authenticate, your authentication token seems to be invalid

### ISSUE THREAD

**Issue by 50Wliu** [microsoft/azure-devops-extension-tasks#816]
On a self-hosted pool, TfxInstaller@4 fails with the following:
```
Starting: Install tfx-cli
==============================================================================
Task         : Use Node CLI for Azure DevOps (tfx-cli)
Description  : Installs the Node CLI for Azure DevOps (tfx-cli) on your agent.
Version      : 4.3.146
Author       : Microsoft Corporation
Help         : 
==============================================================================
C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files\nodejs\npm.cmd" show tfx-cli versions --json"
npm ERR! code E401
{
npm ERR! Unable to authenticate, your authentication token seems to be invalid.
  "error": {
npm ERR! To correct this please trying logging in again with:
    "code": "E401",
npm ERR!     npm login
    "summary": "Unable to authenticate, your authentication token seems to be invalid.",

    "detail": "To correct this please trying logging in again with:\n    npm login"
npm ERR! A complete log of this run can be found in: C:\npm\cache\_logs\2024-02-20T19_09_34_298Z-debug-0.log
  }
}
##[error]Unable to find Tfx version 'v0.16.x'
Finishing: Install tfx-cli
```

Which is confusing because tfx-cli should be publicly available. This also works without issue when using the `windows-latest` pool, is there any setup that needs to be done that I'm not aware of?

**Comment by jessehouwing** [comment]
Does your repo contain an npmrc file?

**Comment by jessehouwing** [comment]
The task does a vanilla npm call to communicate, but doesn't specify a source npm reposirory.

If your project or server is configured to look at a different npm reporitosy or has a set of credentials preconfigured, this may happen.

**Comment by 50Wliu** [comment]
Yep, user error. The self-hosted pool checks out by default so we ended up with an .npmrc.

Is there any way this task can be configured to ignore .npmrcs?

**Comment by jessehouwing** [comment]
Others may want to use this Azure DevOps as a proxy feed. It's really up to the user to make sure the settings make sense.

You can always run npm config commands prior to running the TFX installer task or add a step to rename the npmrc (temporarily). In the 6 years I've maintained this task, you're the first to bump into this problem, well the first to report it.
